# Generated by Django 5.2.5 on 2025-08-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
